services:
  finance-app:
    build: .
    container_name: kite-app
    ports:
      # - "100.66.97.99:8555:8555"
      - "8777:8777"
    volumes:
      - .:/app                   # ← mount your source in
      - /app/__pycache__         # ← optional: ignore container bytecode
    command:
      - uvicorn
      - main:app
      - --host
      - 0.0.0.0
      - --port
      - "8777"
      - --reload                 # ← enable hot-reload
    restart: always
    networks:
      - db-net
      - caddy-net
    env_file:
      - .env
    depends_on:
      - redis


  frontend:
    build: ./frontend
    container_name: kite-frontend
    ports:
      - "8999:80" # Default port for many dev servers, change if needed
    volumes:
      - ./frontend:/app
      - /app/node_modules
    #command: npm start # Or yarn start, npm run dev, etc.
    networks:
      - db-net
      - caddy-net
    depends_on:
      - finance-app
    restart: always

  meilisearch:
    image: getmeili/meilisearch:latest
    volumes:
      - ./meili_data:/data.ms
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=9VZU4Gl2cmca-7FrlXY96bawuYwfFIMkpvohNrMaKCU
    command: ["meilisearch", "--master-key=9VZU4Gl2cmca-7FrlXY96bawuYwfFIMkpvohNrMaKCU"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - db-net
      - caddy-net
    restart: always

  redis:
    image: "redis:alpine"
    container_name: kite-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data 
    networks:
      - db-net
      - caddy-net
    restart: always


networks:
  db-net:
    external: true
  caddy-net:
    external: true
