"""Shared modular algo runtime package."""

from .models import (
    ActionType,
    AlgoCheckpoint,
    AlgoInstance,
    AlgoLifecycleState,
    CandleSeriesSpec,
    DependencySpec,
    IndicatorSpec,
    MarketDataMode,
    NoopAction,
    NotifyAction,
    OptionExpiryMode,
    OptionReadSpec,
    OptionView,
    OrderScope,
    OrderIntent,
    PositionFilter,
    Snapshot,
    StatePatchAction,
    TriggerEvent,
    TriggerType,
)
from .registry import AlgoRegistry, RegistryError
from .repository import InMemoryAlgoRepository, SqlAlchemyAlgoRepository
from .indicators import BuiltInIndicatorReader, compute_ema_series

__all__ = [
    "ActionType",
    "AlgoCheckpoint",
    "AlgoInstance",
    "AlgoLifecycleState",
    "AlgoRegistry",
    "CandleSeriesSpec",
    "DependencySpec",
    "IndicatorSpec",
    "MarketDataMode",
    "NoopAction",
    "NotifyAction",
    "OptionExpiryMode",
    "OptionReadSpec",
    "OptionView",
    "OrderScope",
    "OrderIntent",
    "PositionFilter",
    "RegistryError",
    "Snapshot",
    "StatePatchAction",
    "TriggerEvent",
    "TriggerType",
    "InMemoryAlgoRepository",
    "SqlAlchemyAlgoRepository",
    "BuiltInIndicatorReader",
    "compute_ema_series",
]
