"""operator controls: stop request columns + bounded job logs.

Revision ID: 20260915_000023
Revises: 20260915_000022
Create Date: 2026-09-15 00:00:23

Purely additive:

- ``strategy_jobs`` gains ``stop_requested_at`` / ``stop_requested_by`` so an
  operator Stop is durable, attributed and bound to the immutable attempt.
- a new ``strategy_job_logs`` table stores bounded, redacted child-log chunks
  pushed by the supervisor through the lifecycle API. The API never reads the
  supervisor container's filesystem.

No existing table is altered destructively and no backfill is required.
"""

from alembic import op

revision = "20260915_000023"
down_revision = "20260915_000022"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        "ALTER TABLE public.strategy_jobs ADD COLUMN IF NOT EXISTS stop_requested_at TIMESTAMPTZ"
    )
    op.execute(
        "ALTER TABLE public.strategy_jobs ADD COLUMN IF NOT EXISTS stop_requested_by TEXT"
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS public.strategy_job_logs (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            job_id TEXT NOT NULL REFERENCES public.strategy_jobs(id) ON DELETE CASCADE,
            attempt INTEGER NOT NULL,
            seq INTEGER NOT NULL,
            content TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_strategy_job_logs_seq UNIQUE (job_id, attempt, seq)
        );
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_strategy_job_logs_job
            ON public.strategy_job_logs (job_id, attempt, seq);
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS public.strategy_job_logs")
    op.execute("ALTER TABLE public.strategy_jobs DROP COLUMN IF EXISTS stop_requested_by")
    op.execute("ALTER TABLE public.strategy_jobs DROP COLUMN IF EXISTS stop_requested_at")
