package dispatch

// Code generated from endpoint_manifest.py + tools/*.py.
// Hand-fix fidelity corrections here; the manifest is the source of truth.

var Table = map[string]Dispatch{
	"get_capabilities":            {Method: "GET", Path: "/worker/health", RunIDField: "", Lease: false, Kind: KindCapabilities},
	"list_runs":                   {Method: "GET", Path: "/worker/runs", RunIDField: "", Lease: false},
	"get_run":                     {Method: "GET", Path: "/worker/runs/{strategy_run_id}", RunIDField: "strategy_run_id", Lease: false},
	"get_run_health":              {Method: "GET", Path: "/worker/runs/{strategy_run_id}", RunIDField: "strategy_run_id", Lease: false},
	"get_funds":                   {Method: "GET", Path: "/worker/funds", RunIDField: "", Lease: false},
	"get_run_funds":               {Method: "GET", Path: "/worker/runs/{strategy_run_id}/funds", RunIDField: "strategy_run_id", Lease: false},
	"get_account_portfolio":       {Method: "GET", Path: "/worker/account/portfolio", RunIDField: "", Lease: false},
	"search_instruments":          {Method: "GET", Path: "/worker/market/instruments/search", RunIDField: "", Lease: false},
	"resolve_instruments":         {Method: "POST", Path: "/worker/market/instruments/resolve", RunIDField: "", Lease: false},
	"get_quotes":                  {Method: "POST", Path: "/worker/market/quotes", RunIDField: "", Lease: false},
	"get_market_snapshot":         {Method: "POST", Path: "/worker/market/snapshot", RunIDField: "", Lease: false},
	"get_market_depth":            {Method: "POST", Path: "/worker/market/quotes", RunIDField: "", Lease: false, Shaper: ShapeDepthView},
	"get_candles":                 {Method: "GET", Path: "/worker/market/candles", RunIDField: "", Lease: false},
	"get_current_candle":          {Method: "GET", Path: "/worker/market/candles", RunIDField: "", Lease: false, Shaper: ShapeCurrentCandle},
	"get_historical_candles":      {Method: "GET", Path: "/worker/market/history", RunIDField: "", Lease: false},
	"request_history":             {Method: "GET", Path: "/worker/market/history", RunIDField: "", Lease: false},
	"get_market_calendar":         {Method: "GET", Path: "/worker/market/calendar", RunIDField: "", Lease: false},
	"get_market_calendar_status":  {Method: "GET", Path: "/worker/market/calendar/status", RunIDField: "", Lease: false},
	"get_index_constituents":      {Method: "GET", Path: "/worker/market/indices/{source_list}", RunIDField: "", Lease: false},
	"get_index_status":            {Method: "GET", Path: "/worker/market/indices/{source_list}/status", RunIDField: "", Lease: false},
	"get_fundamentals_features":   {Method: "GET", Path: "/worker/fundamentals/features", RunIDField: "", Lease: false},
	"get_fundamentals_statements": {Method: "GET", Path: "/worker/fundamentals/statements", RunIDField: "", Lease: false},
	"get_fundamentals_status":     {Method: "GET", Path: "/worker/fundamentals/status", RunIDField: "", Lease: false},
	"refresh_fundamentals":        {Method: "POST", Path: "/worker/fundamentals/sync", RunIDField: "", Lease: false},
	"create_run":                  {Method: "POST", Path: "/worker/runs", RunIDField: "", Lease: false},
	"check_run_safety":            {Method: "GET", Path: "/worker/runs/{strategy_run_id}/safety-check", RunIDField: "", Lease: false},
	"preview_order":               {Method: "POST", Path: "/worker/runs/{strategy_run_id}/preview/order", RunIDField: "", Lease: false},
	"preview_basket":              {Method: "POST", Path: "/worker/runs/{strategy_run_id}/preview/basket", RunIDField: "", Lease: false},
	"place_order":                 {Method: "POST", Path: "/worker/runs/{strategy_run_id}/intents", RunIDField: "strategy_run_id", Lease: true, PreCheckSafety: true},
	"place_basket":                {Method: "POST", Path: "/worker/runs/{strategy_run_id}/baskets", RunIDField: "strategy_run_id", Lease: true, PreCheckSafety: true},
	"list_orders":                 {Method: "GET", Path: "/worker/orders", RunIDField: "", Lease: false},
	"list_trades":                 {Method: "GET", Path: "/worker/trades", RunIDField: "", Lease: false},
	"get_order":                   {Method: "GET", Path: "/worker/orders/{order_id}", RunIDField: "", Lease: false},
	"get_order_history":           {Method: "GET", Path: "/worker/orders/{order_id}/history", RunIDField: "", Lease: false},
	"modify_order":                {Method: "POST", Path: "/worker/orders/{order_id}/modify", RunIDField: "strategy_run_id", Lease: true},
	"cancel_order":                {Method: "POST", Path: "/worker/orders/{order_id}/cancel", RunIDField: "strategy_run_id", Lease: true},
	"list_baskets":                {Method: "GET", Path: "/worker/runs/{strategy_run_id}/baskets", RunIDField: "", Lease: false},
	"get_basket":                  {Method: "GET", Path: "/worker/runs/{strategy_run_id}/baskets/{basket_execution_id}", RunIDField: "strategy_run_id", Lease: false},
	"create_bracket":              {Method: "POST", Path: "/worker/runs/{strategy_run_id}/brackets", RunIDField: "strategy_run_id", Lease: true},
	"list_brackets":               {Method: "GET", Path: "/worker/runs/{strategy_run_id}/brackets", RunIDField: "", Lease: false},
	"get_bracket":                 {Method: "GET", Path: "/worker/runs/{strategy_run_id}/brackets/{bracket_intent_id}", RunIDField: "strategy_run_id", Lease: false},
	"cancel_bracket":              {Method: "POST", Path: "/worker/runs/{strategy_run_id}/brackets/{bracket_intent_id}/cancel", RunIDField: "strategy_run_id", Lease: true},
	"create_gtt":                  {Method: "POST", Path: "/worker/gtt/triggers", RunIDField: "", Lease: false},
	"list_gtts":                   {Method: "GET", Path: "/worker/gtt/triggers", RunIDField: "", Lease: false},
	"get_gtt":                     {Method: "GET", Path: "/worker/gtt/triggers/{trigger_id}", RunIDField: "", Lease: false},
	"modify_gtt":                  {Method: "PUT", Path: "/worker/gtt/triggers/{trigger_id}", RunIDField: "", Lease: false},
	"delete_gtt":                  {Method: "DELETE", Path: "/worker/gtt/triggers/{trigger_id}", RunIDField: "", Lease: false},
	"exit_run":                    {Method: "POST", Path: "/worker/runs/{strategy_run_id}/exit", RunIDField: "strategy_run_id", Lease: true},
	"update_run_risk":             {Method: "PATCH", Path: "/worker/runs/{strategy_run_id}/risk", RunIDField: "strategy_run_id", Lease: true},
	"update_run_protection":       {Method: "PATCH", Path: "/worker/runs/{strategy_run_id}/protection", RunIDField: "strategy_run_id", Lease: true},
	"get_run_protection":          {Method: "GET", Path: "/worker/runs/{strategy_run_id}/protection", RunIDField: "", Lease: false},
	"get_run_pnl":                 {Method: "GET", Path: "/worker/runs/{strategy_run_id}/pnl", RunIDField: "", Lease: false},
	"list_run_timeline":           {Method: "GET", Path: "/worker/runs/{strategy_run_id}/timeline", RunIDField: "", Lease: false},
	"list_execution_events":       {Method: "GET", Path: "/worker/runs/{strategy_run_id}/execution-events", RunIDField: "", Lease: false},
	"log_run_decision":            {Method: "POST", Path: "/worker/runs/{strategy_run_id}/decision-events", RunIDField: "", Lease: false},
	"list_option_expiries":        {Method: "GET", Path: "/worker/options/underlyings/{underlying}/expiries", RunIDField: "", Lease: false},
	"get_option_chain":            {Method: "GET", Path: "/worker/options/underlyings/{underlying}/chain", RunIDField: "", Lease: false},
	"get_option_mini_chain":       {Method: "GET", Path: "/worker/options/underlyings/{underlying}/mini-chain", RunIDField: "", Lease: false},
	"get_option_greeks":           {Method: "GET", Path: "/worker/options/underlyings/{underlying}/greeks", RunIDField: "", Lease: false},
	"get_option_pcr":              {Method: "GET", Path: "/worker/options/underlyings/{underlying}/analytics/pcr", RunIDField: "", Lease: false},
	"get_option_max_pain":         {Method: "GET", Path: "/worker/options/underlyings/{underlying}/analytics/max-pain", RunIDField: "", Lease: false},
	"resolve_option_contracts":    {Method: "POST", Path: "/worker/options/underlyings/{underlying}/selection/resolve", RunIDField: "", Lease: false},
	"preview_option_strategy":     {Method: "POST", Path: "/worker/options/strategies/preview", RunIDField: "", Lease: false},
	"preview_option_entry":        {Method: "POST", Path: "/worker/options/runs/{strategy_run_id}/preview-entry", RunIDField: "strategy_run_id", Lease: false, AuthRun: true},
	"preview_option_exit":         {Method: "POST", Path: "/worker/options/runs/{strategy_run_id}/preview-exit", RunIDField: "strategy_run_id", Lease: false, AuthRun: true},
	"create_option_run":           {Method: "POST", Path: "/worker/options/runs", RunIDField: "strategy_run_id", Lease: true, AuthRun: true, OptCtx: true, ResolveLegs: true},
	"enter_option_run":            {Method: "POST", Path: "/worker/options/runs/{strategy_run_id}/enter", RunIDField: "strategy_run_id", Lease: true, AuthRun: true, OptCtx: true},
	"exit_option_run":             {Method: "POST", Path: "/worker/options/runs/{strategy_run_id}/exit", RunIDField: "strategy_run_id", Lease: true, AuthRun: true, OptCtx: true},
	"get_option_run_state":        {Method: "GET", Path: "/worker/options/runs/{strategy_run_id}/state", RunIDField: "strategy_run_id", Lease: false, AuthRun: true},
	"update_option_protection":    {Method: "PUT", Path: "/worker/options/runs/{strategy_run_id}/protection", RunIDField: "strategy_run_id", Lease: true, AuthRun: true},
	"get_option_protection":       {Method: "GET", Path: "/worker/options/runs/{strategy_run_id}/protection/state", RunIDField: "strategy_run_id", Lease: false, AuthRun: true},
	"replay_option_protection":    {Method: "POST", Path: "/worker/options/runs/{strategy_run_id}/protection/replay", RunIDField: "strategy_run_id", Lease: false, AuthRun: true},
	"calculate_indicator":         {Method: "POST", Path: "/worker/indicators", RunIDField: "", Lease: false},
}
